# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Harrison\code\rpa_footprints-main\plugin_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyPluginDialog(object):
    def setupUi(self, MyPluginDialog):
        MyPluginDialog.setObjectName("MyPluginDialog")
        self.mainLayout = QtWidgets.QVBoxLayout(MyPluginDialog)
        self.mainLayout.setObjectName("mainLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelInputFolder = QtWidgets.QLabel(MyPluginDialog)
        self.labelInputFolder.setObjectName("labelInputFolder")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelInputFolder)
        self.inputFolderLayout = QtWidgets.QHBoxLayout()
        self.inputFolderLayout.setObjectName("inputFolderLayout")
        self.inputFolderLine = QtWidgets.QLineEdit(MyPluginDialog)
        self.inputFolderLine.setObjectName("inputFolderLine")
        self.inputFolderLayout.addWidget(self.inputFolderLine)
        self.btnInputFolder = QtWidgets.QPushButton(MyPluginDialog)
        self.btnInputFolder.setObjectName("btnInputFolder")
        self.inputFolderLayout.addWidget(self.btnInputFolder)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.inputFolderLayout)
        self.labelOutputFolder = QtWidgets.QLabel(MyPluginDialog)
        self.labelOutputFolder.setObjectName("labelOutputFolder")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelOutputFolder)
        self.outputFolderLayout = QtWidgets.QHBoxLayout()
        self.outputFolderLayout.setObjectName("outputFolderLayout")
        self.outputFolderLine = QtWidgets.QLineEdit(MyPluginDialog)
        self.outputFolderLine.setObjectName("outputFolderLine")
        self.outputFolderLayout.addWidget(self.outputFolderLine)
        self.btnOutputFolder = QtWidgets.QPushButton(MyPluginDialog)
        self.btnOutputFolder.setObjectName("btnOutputFolder")
        self.outputFolderLayout.addWidget(self.btnOutputFolder)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.outputFolderLayout)
        self.mainLayout.addLayout(self.formLayout)
        self.btnToggleAdvancedOptions = QtWidgets.QPushButton(MyPluginDialog)
        self.btnToggleAdvancedOptions.setObjectName("btnToggleAdvancedOptions")
        self.mainLayout.addWidget(self.btnToggleAdvancedOptions)
        self.advancedOptionsGroup = QtWidgets.QGroupBox(MyPluginDialog)
        self.advancedOptionsGroup.setObjectName("advancedOptionsGroup")
        self.advancedOptionsLayout = QtWidgets.QFormLayout(self.advancedOptionsGroup)
        self.advancedOptionsLayout.setObjectName("advancedOptionsLayout")
        self.labelHeight = QtWidgets.QLabel(self.advancedOptionsGroup)
        self.labelHeight.setObjectName("labelHeight")
        self.advancedOptionsLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelHeight)
        self.heightLine = QtWidgets.QLineEdit(self.advancedOptionsGroup)
        self.heightLine.setObjectName("heightLine")
        self.advancedOptionsLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.heightLine)
        self.labelSensorWidth = QtWidgets.QLabel(self.advancedOptionsGroup)
        self.labelSensorWidth.setObjectName("labelSensorWidth")
        self.advancedOptionsLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelSensorWidth)
        self.sensorWidthLine = QtWidgets.QLineEdit(self.advancedOptionsGroup)
        self.sensorWidthLine.setObjectName("sensorWidthLine")
        self.advancedOptionsLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sensorWidthLine)
        self.labelSensorHeight = QtWidgets.QLabel(self.advancedOptionsGroup)
        self.labelSensorHeight.setObjectName("labelSensorHeight")
        self.advancedOptionsLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelSensorHeight)
        self.sensorHeightLine = QtWidgets.QLineEdit(self.advancedOptionsGroup)
        self.sensorHeightLine.setObjectName("sensorHeightLine")
        self.advancedOptionsLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sensorHeightLine)
        self.labelGimbalPitch = QtWidgets.QLabel(self.advancedOptionsGroup)
        self.labelGimbalPitch.setObjectName("labelGimbalPitch")
        self.advancedOptionsLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelGimbalPitch)
        self.gimbalPitchLine = QtWidgets.QLineEdit(self.advancedOptionsGroup)
        self.gimbalPitchLine.setObjectName("gimbalPitchLine")
        self.advancedOptionsLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.gimbalPitchLine)
        self.mainLayout.addWidget(self.advancedOptionsGroup)
        self.runButton = QtWidgets.QPushButton(MyPluginDialog)
        self.runButton.setObjectName("runButton")
        self.mainLayout.addWidget(self.runButton)

        self.retranslateUi(MyPluginDialog)

    def retranslateUi(self, MyPluginDialog):
        _translate = QtCore.QCoreApplication.translate
        MyPluginDialog.setWindowTitle(_translate("MyPluginDialog", "RPA Footprints"))
        self.labelInputFolder.setText(_translate("MyPluginDialog", "Input Folder:"))
        self.btnInputFolder.setText(_translate("MyPluginDialog", "Browse..."))
        self.labelOutputFolder.setText(_translate("MyPluginDialog", "Output Folder:"))
        self.btnOutputFolder.setText(_translate("MyPluginDialog", "Browse..."))
        self.btnToggleAdvancedOptions.setText(_translate("MyPluginDialog", "Show Advanced Options"))
        self.advancedOptionsGroup.setTitle(_translate("MyPluginDialog", "Advanced Options"))
        self.labelHeight.setText(_translate("MyPluginDialog", "Height:"))
        self.labelSensorWidth.setText(_translate("MyPluginDialog", "Sensor Width:"))
        self.labelSensorHeight.setText(_translate("MyPluginDialog", "Sensor Height:"))
        self.labelGimbalPitch.setText(_translate("MyPluginDialog", "Gimbal Pitch (degrees):"))
        self.runButton.setText(_translate("MyPluginDialog", "Run"))
